---
- name: Initiate Host file template with GUID
  hosts: localhost
  roles:
    - inventory

- name: Prepare Environment Play
  hosts: all
  roles:
    - prep-env

- name: Import prerequisites playbook
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"

- name: Deploy ocp cluster playbook
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml"

- name: AFTER INSTALLATION
  hosts: all,localhost
  roles:
    - AFTER-INSTALL

- name: SMOKE TEST ROLE
  hosts: localhost
  roles:
    - SMOKE-TEST-ROLE

- name: Deploy Jenkins
  hosts: localhost
  roles:
    - cicd

- name: Deploy OpenShift Tasks Project
  hosts: localhost
  roles:
    - deploy-tasks-app

- name: Prepare cluster for Multitenant project setup
  hosts: masters,localhost
  roles:
    - multitenant

- name: On Board users groups projects and applications
  hosts: masters,localhost
  roles:
    - deploy-client-projects
